ci test

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -21,6 +21,7 @@ jobs:
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
-    - run: ret=$(echo `find . -name "server.js" -exec sh -c 'node --check {}; if [ $? -eq 0 ]; then echo PASS {} $'\n'; else echo FAIL {} $'\n'; fi;' \; ;`;)
-    - run: echo $ret
-    - run: if [[ $ret == *"FAIL"* ]]; then exit 1; fi;
+      run: |
+        ret=$(echo `find . -name "server.js" -exec sh -c 'node --check {}; if [ $? -eq 0 ]; then echo PASS {} $'\n'; else echo FAIL {} $'\n'; fi;' \; ;`;)
+        echo $ret
+        if [[ $ret == *"FAIL"* ]]; then exit 1; fi;
