Squashed commit of the following:
commit 75b7e3ca17adca75e4ff03467ed21264e9bf915e
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 03:59:15 2021 +0900

    ci complete

commit 26d649920815290176ec4bcb608d5ec31b838545
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 03:58:19 2021 +0900

    ci test to make error

commit c9abe2d1022d833784a99effaec5ed27ab55bf21
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 03:56:46 2021 +0900

    ci test

commit 8d089a6343c08a74b09cbde7972478c05f05995b
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 03:56:00 2021 +0900

    ci test

commit ae31002733b082613cc0ef0097d78229297fb014
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 03:54:19 2021 +0900

    ci test

commit 692382f8f6ad147b4c10c71433e50e506d3e8fe4
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 03:52:39 2021 +0900

    ci test

commit e309597d4554036c015d3a8435420fb9886c6f7e
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 02:49:22 2021 +0900

    testing condition to make error

commit bb9124513912a13cd4d03e6c6fc359b235b8c6ef
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 02:43:48 2021 +0900

    updated ci to actived for pushes of test branch

commit ba0c681d426bbc9b5a0863145053e954110ae027
Author: miho73 <hyrexfiels@gmail.com>
Date:   Mon Jun 28 02:40:42 2021 +0900

    test ci to make error

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -2,7 +2,7 @@ name: Node.js CI
 
 on:
   push:
-    branches: [ main ]
+    branches: [ main, new-ci-test ]
   pull_request:
     branches: [ main ]
 
@@ -21,6 +21,8 @@ jobs:
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
-    - run: npm ci
-    - run: npm run build --if-present
-    - run: npm test
+    - name: Run test
+      run: |
+        ret=$(echo `find . -name "*.js" -exec sh -c 'node --check {}; if [ $? -eq 0 ]; then echo PASS {} $'\n'; else echo FAIL {} $'\n'; fi;' \; ;`;)
+        echo $ret
+        if [[ $ret == *"FAIL"* ]]; then exit 1; fi;
